apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: .
    repoURL: https://github.com/ronanbarrett/canary
    targetRevision: {{ .Values.spec.source.targetRevision }}
  spec:
    syncPolicy:
      automated: {} #always track git changes and auto sync
